export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
 return (
    <html lang="en">
      <body style={{border: "2px solid gray", margin: "5px", padding: "5px"}}>{children}</body>
    </html>
  )
}
